name: Test Swiple Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Validate Dataset
      uses: ./
      id: swiple-action
      with:
        api_base_url: ${{ secrets.API_BASE_URL }}
        ui_base_url: http://127.0.0.1:3000
        dataset_id: ${{ secrets.DATASET_ID }}
        username: ${{ secrets.API_USERNAME }}
        password: ${{ secrets.API_PASSWORD }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        require_all_passed: 'true'